name: openapi
version: 1.0.0-alpha
description: OpenAPI schemas and metadata for Dart. Intended to help generate code from Swagger definitions.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  meta: ^1.0.0