// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// Target: library
// **************************************************************************

// Generated by owl 0.1.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'schemas.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

// **************************************************************************
// Generator: JsonGenerator
// Target: class Schema
// **************************************************************************

/// Mapper for Schema
abstract class SchemaMapper {
  /// Converts an instance of Schema to Map.
  static Map<String, dynamic> map(Schema object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('swagger', object.swagger)
          ..put('host', object.host)
          ..put('basePath', object.basePath)
          ..put('info', InfoMapper.map(object.info))
          ..put('schemes', object.schemes?.toList())
          ..put('consumes', object.consumes?.toList())
          ..put('produces', object.produces?.toList())
          ..put('security', object.security)
          ..put('tags', object.tags?.map(TagMapper.map)?.toList())
          ..put('externalDocs',
              ExternalDocumentationMapper.map(object.externalDocs))
          ..put('paths', object.paths))
        .toMap();
  }

  /// Converts a Map to an instance of Schema.
  static Schema parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Schema object = new Schema();
    object.swagger = map['swagger'];
    object.host = map['host'];
    object.basePath = map['basePath'];
    object.info = InfoMapper.parse(map['info']);

    // ignore: avoid_as
    object.schemes = (map['schemes'] as List<String>)?.toList();

    // ignore: avoid_as
    object.consumes = (map['consumes'] as List<String>)?.toList();

    // ignore: avoid_as
    object.produces = (map['produces'] as List<String>)?.toList();
    object.security = map['security'];

    // ignore: avoid_as
    object.tags =
        (map['tags'] as List<dynamic>)?.map(TagMapper.parse)?.toList();
    object.externalDocs =
        ExternalDocumentationMapper.parse(map['externalDocs']);
    object.paths = map['paths'];
    return object;
  }

  /// Converts a JSON string to an instance of Schema.
  static Schema fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Schema to JSON string.
  static String toJson(Schema object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Info
// **************************************************************************

/// Mapper for Info
abstract class InfoMapper {
  /// Converts an instance of Info to Map.
  static Map<String, dynamic> map(Info object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)).toMap();
  }

  /// Converts a Map to an instance of Info.
  static Info parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Info object = new Info();
    return object;
  }

  /// Converts a JSON string to an instance of Info.
  static Info fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Info to JSON string.
  static String toJson(Info object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Operation
// **************************************************************************

/// Mapper for Operation
abstract class OperationMapper {
  /// Converts an instance of Operation to Map.
  static Map<String, dynamic> map(Operation object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('tags', object.tags?.toList())
          ..put('consumes', object.consumes?.toList())
          ..put('produces', object.produces?.toList())
          ..put('schemes', object.schemes?.toList())
          ..put('summary', object.summary)
          ..put('description', object.description)
          ..put('operationId', object.operationId)
          ..put('externalDocs',
              ExternalDocumentationMapper.map(object.externalDocs))
          ..put('deprecated', object.deprecated))
        .toMap();
  }

  /// Converts a Map to an instance of Operation.
  static Operation parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Operation object = new Operation();
    // ignore: avoid_as
    object.tags = (map['tags'] as List<String>)?.toList();

    // ignore: avoid_as
    object.consumes = (map['consumes'] as List<String>)?.toList();

    // ignore: avoid_as
    object.produces = (map['produces'] as List<String>)?.toList();

    // ignore: avoid_as
    object.schemes = (map['schemes'] as List<String>)?.toList();
    object.summary = map['summary'];
    object.description = map['description'];
    object.operationId = map['operationId'];
    object.externalDocs =
        ExternalDocumentationMapper.parse(map['externalDocs']);
    object.deprecated = map['deprecated'];
    return object;
  }

  /// Converts a JSON string to an instance of Operation.
  static Operation fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Operation to JSON string.
  static String toJson(Operation object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class ExternalDocumentation
// **************************************************************************

/// Mapper for ExternalDocumentation
abstract class ExternalDocumentationMapper {
  /// Converts an instance of ExternalDocumentation to Map.
  static Map<String, dynamic> map(ExternalDocumentation object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('description', object.description)
          ..put('url', object.url))
        .toMap();
  }

  /// Converts a Map to an instance of ExternalDocumentation.
  static ExternalDocumentation parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ExternalDocumentation object = new ExternalDocumentation();
    object.description = map['description'];
    object.url = map['url'];
    return object;
  }

  /// Converts a JSON string to an instance of ExternalDocumentation.
  static ExternalDocumentation fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ExternalDocumentation to JSON string.
  static String toJson(ExternalDocumentation object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Parameters
// **************************************************************************

/// Mapper for Parameters
abstract class ParametersMapper {
  /// Converts an instance of Parameters to Map.
  static Map<String, dynamic> map(Parameters object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)).toMap();
  }

  /// Converts a Map to an instance of Parameters.
  static Parameters parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Parameters object = new Parameters();
    return object;
  }

  /// Converts a JSON string to an instance of Parameters.
  static Parameters fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Parameters to JSON string.
  static String toJson(Parameters object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Reference
// **************************************************************************

/// Mapper for Reference
abstract class ReferenceMapper {
  /// Converts an instance of Reference to Map.
  static Map<String, dynamic> map(Reference object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)).toMap();
  }

  /// Converts a Map to an instance of Reference.
  static Reference parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Reference object = new Reference();
    return object;
  }

  /// Converts a JSON string to an instance of Reference.
  static Reference fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Reference to JSON string.
  static String toJson(Reference object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Responses
// **************************************************************************

/// Mapper for Responses
abstract class ResponsesMapper {
  /// Converts an instance of Responses to Map.
  static Map<String, dynamic> map(Responses object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)).toMap();
  }

  /// Converts a Map to an instance of Responses.
  static Responses parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Responses object = new Responses();
    return object;
  }

  /// Converts a JSON string to an instance of Responses.
  static Responses fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Responses to JSON string.
  static String toJson(Responses object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Response
// **************************************************************************

/// Mapper for Response
abstract class ResponseMapper {
  /// Converts an instance of Response to Map.
  static Map<String, dynamic> map(Response object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)).toMap();
  }

  /// Converts a Map to an instance of Response.
  static Response parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Response object = new Response();
    return object;
  }

  /// Converts a JSON string to an instance of Response.
  static Response fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Response to JSON string.
  static String toJson(Response object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Tag
// **************************************************************************

/// Mapper for Tag
abstract class TagMapper {
  /// Converts an instance of Tag to Map.
  static Map<String, dynamic> map(Tag object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('name', object.name)
          ..put('description', object.description)
          ..put('externalDocs',
              ExternalDocumentationMapper.map(object.externalDocs)))
        .toMap();
  }

  /// Converts a Map to an instance of Tag.
  static Tag parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Tag object = new Tag();
    object.name = map['name'];
    object.description = map['description'];
    object.externalDocs =
        ExternalDocumentationMapper.parse(map['externalDocs']);
    return object;
  }

  /// Converts a JSON string to an instance of Tag.
  static Tag fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Tag to JSON string.
  static String toJson(Tag object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class SecurityScheme
// **************************************************************************

/// Mapper for SecurityScheme
abstract class SecuritySchemeMapper {
  /// Converts an instance of SecurityScheme to Map.
  static Map<String, dynamic> map(SecurityScheme object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('type', object.type)
          ..put('description', object.description)
          ..put('name', object.name)
          ..put('flow', object.flow)
          ..put('authorizationUrl', object.authorizationUrl)
          ..put('tokenUrl', object.tokenUrl)
          ..put('in', object.in_)
          ..put('scopes', object.scopes))
        .toMap();
  }

  /// Converts a Map to an instance of SecurityScheme.
  static SecurityScheme parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SecurityScheme object = new SecurityScheme();
    object.type = map['type'];
    object.description = map['description'];
    object.name = map['name'];
    object.flow = map['flow'];
    object.authorizationUrl = map['authorizationUrl'];
    object.tokenUrl = map['tokenUrl'];
    object.in_ = map['in'];
    object.scopes = map['scopes'];
    return object;
  }

  /// Converts a JSON string to an instance of SecurityScheme.
  static SecurityScheme fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SecurityScheme to JSON string.
  static String toJson(SecurityScheme object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
